export const {
  NEXT_PUBLIC_WORDPRESS_API_URL,
  NEXT_PUBLIC_MAPBOX_API_TOKEN,
  NEXT_PUBLIC_API_KEY,
  NEXT_PUBLIC_ACCESS_KEY,
  NEXT_PUBLIC_IWS_TEST_API_URL,
  NEXT_PUBLIC_CONTENT_URL,
  NEXT_PUBLIC_EMAIL_FROM_ADDRESS,
  NEXT_PUBLIC_EMAIL_RECIPIENT_FOR_QUOTES,
  DATABASE_URL,
  NEXT_PUBLIC_APP_URL,
} = process.env
